# Generated by Django 4.1.2 on 2022-11-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=100, verbose_name='ifsc')),
                ('bank_name', models.CharField(max_length=250, verbose_name='bank_name')),
                ('bank_id', models.IntegerField(max_length=20, verbose_name='bank_id')),
                ('branch', models.CharField(max_length=100, verbose_name='branch')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('district', models.CharField(max_length=100, verbose_name='district')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
            ],
        ),
    ]
