# Generated by Django 4.1.2 on 2022-11-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bank_bank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='banks',
            fields=[
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'bank',
            },
        ),
    ]
