# Generated by Django 4.1.2 on 2022-11-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_banks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.CharField(max_length=250, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='branch',
            field=models.CharField(max_length=250, verbose_name='branch'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='city',
            field=models.CharField(max_length=250, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='district',
            field=models.CharField(max_length=250, verbose_name='district'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc',
            field=models.CharField(max_length=250, verbose_name='ifsc'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='state',
            field=models.CharField(max_length=250, verbose_name='state'),
        ),
    ]
