# Generated by Django 4.1.2 on 2022-11-02 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_bank_address_alter_bank_branch_alter_bank_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('ifsc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('bank_id', models.BigIntegerField(blank=True, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'bank branch',
                'verbose_name_plural': 'bank branches',
                'db_table': 'bank_branches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('ifsc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'db_table': 'branches',
            },
        ),
        migrations.DeleteModel(
            name='bank',
        ),
        migrations.AlterModelTable(
            name='banks',
            table='banks',
        ),
        migrations.AddField(
            model_name='branches',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.banks'),
        ),
    ]
